version: '3.5'

services:
  
  couch:
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=dev
    ports:
      - "5984:5984"
    volumes:
      - type: volume
        source: couch-data
        target: /opt/couchdb/data
      - type: volume
        source: couch-log
        target: /opt/couchdb/log
      - type: volume
        source: couch-config
        target: /opt/couchdb/etc/local.d


  # liftbridge:
  #   ports:
  #     - "4222:4222"
  #     - "6222:6222"
  #     - "8222:8222"
  #     - "9292:9292"
  #   environment: 
  #     - NATS_CLUSTER = default
  #     - NATS_CLIENT = default
  #     - NATS_SERVER = nats://liftbridge:4222

  # natsboard:
  #   ports:
  #    - "3030:3000"  


  nats:
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    environment: 
      - NATS_CLUSTER=default
      - NATS_CLIENT=default
      - NATS_SERVER=nats://nats:4222
   
  
  eventstore:
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_DB=/var/lib/eventstore-data
      - EVENTSTORE_INDEX=/var/lib/eventstore-index
      - EVENTSTORE_LOG=/var/log/eventstore
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_DEV=true
      - EVENTSTORE_INSECURE=true
    ports:
      - "2112:2112"
      - "2113:2113"
      - "1113:1113"
      - "1112:1112"
    volumes:
      - type: volume
        source: eventstore-data
        target: /var/lib/eventstore-data
      - type: volume
        source: eventstore-index
        target: /var/lib/eventstore-index
      - type: volume
        source: eventstore-logs
        target: /var/log/eventstore


  es01:
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: volume
        source: es01-data
        target: /usr/share/elasticsearch/data 
    ports:
      - 9200:9200
          
  es02:
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: volume
        source: es02-data
        target: /usr/share/elasticsearch/data 
          
  es03:
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: volume
        source: es03-data
        target: /usr/share/elasticsearch/data 

  kib01:
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
          


volumes:

  couch-data:
    driver: local
    driver_opts: 
      type: none
      device: /volume/couchdb/data
      o: bind

  couch-log:
    driver: local
    driver_opts: 
      type: none
      device: /volume/couchdb/log
      o: bind

  couch-config:
    driver: local
    driver_opts: 
      type: none
      device: /volume/couchdb/config
      o: bind

  eventstore-logs:    
    driver: local
    driver_opts: 
      type: none
      device: /volume/eventstore/logs
      o: bind

  eventstore-data:    
    driver: local
    driver_opts: 
      type: none
      device: /volume/eventstore/data
      o: bind

  eventstore-index:    
    driver: local
    driver_opts: 
      type: none
      device: /volume/eventstore/index
      o: bind

  es01-data:
    driver: local
    driver_opts: 
      type: none
      device: /volume/elastic/data01
      o: bind

  es02-data:
    driver: local
    driver_opts: 
      type: none
      device: /volume/elastic/data02
      o: bind

  es03-data:
    driver: local
    driver_opts: 
      type: none
      device: /volume/elastic/data03
      o: bind


