version: "3.5"

services:

  memphis-http:
    image: local/memphis-http
    build:
      context: ./backend/memphis-http
    env_file:
      - ./backend/memphis-http/.env
    container_name: memphis-http
    depends_on:
      memphis-cluster:
        condition: service_healthy
    restart: on-failure
    pull_policy: always
    networks:
      - dev-net
    ports:
      - "4444:4444"
