version: '3.5'

services:
  mockery:
    image: local/mockery
    build: 
      context: ./tools/mockery
    env_file:
      - ./tools/mockery/.env
    container_name: mockery
    hostname: mockery
    ports:
      - "9666:9666"
    networks:
      - dev-net
    volumes:
      - spacedeck-storage:/app/storage
      - spacedeck-db:/app/database


volumes:
  spacedeck-storage:
    driver: local
    driver_opts: 
      type: none
      device: /volume/spacedeck/storage
      o: bind

  spacedeck-db:
    driver: local
    driver_opts: 
      type: none
      device: /volume/spacedeck/db
      o: bind